import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;//giving type reactnode to children by typescript
}>) {
  return (
    <html lang="en" className="dark bg-black">
      <body className={inter.className}>
        <div className="relative w-full flex justify-center items-center">
        <Navbar/>
        </div>
        
       
        {children}
        </body>
    </html>
  );
}
